development:
  ACCESS_KEY_ID: AKIAI7LLKEWPT2P5JISQ
  SECRET_KEY: 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
  SONGS_BUCKET: playolasongs
  COMMERCIALS_BUCKET: playolacommercials
  COMMENTARIES_BUCKET: playolacommentaries
  UNPROCESSED_SONGS: playolaunprocessedsongs

test:
  ACCESS_KEY_ID: AKIAI7LLKEWPT2P5JISQ
  SECRET_KEY: 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
  SONGS_BUCKET: playolasongstest
  COMMERCIALS_BUCKET: playolacommercialstest
  COMMENTARIES_BUCKET: playolacommentariestest
  UNPROCESSED_SONGS: playolaunprocessedsongstest

production:
  ACCESS_KEY_ID: AKIAI7LLKEWPT2P5JISQ
  SECRET_KEY: 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
  SONGS_BUCKET: playolasongs
  COMMERCIALS_BUCKET: playolacommercials
  COMMENTARIES_BUCKET: playolacommentaries
  UNPROCESSED_SONGS: playolaunprocessedsongs